options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _CLUSTER_NAME: lab-gke
  _REPO: repo-lab

steps:
  # ======================
  # CI – Testes automatizados
  # ======================
  - name: "python:3.12-slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        pip install --no-cache-dir -r requirements.txt
        pytest -q

  # ======================
  # CI – Build da imagem (Dockerfile na raiz)
  # ======================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:$SHORT_SHA",
        "."
      ]

  # ======================
  # CI – Push da imagem
  # ======================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:$SHORT_SHA"
      ]

  # ======================
  # CD – Deploy no GKE (GKE + Secret Manager -> Secret do Kubernetes)
  # ======================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail

        # Acessa o cluster
        gcloud container clusters get-credentials "${_CLUSTER_NAME}" \
          --region "${_REGION}" \
          --project "$PROJECT_ID"

        # Namespace
        kubectl apply -f k8s/namespace.yaml

        # Lê secrets do Secret Manager (runtime)
        DB_USER="$(gcloud secrets versions access latest --secret=db-user)"
        DB_PASSWORD="$(gcloud secrets versions access latest --secret=db-password)"
        DB_NAME="$(gcloud secrets versions access latest --secret=db-name)"

        # Cria/atualiza Secret no Kubernetes (note o $$ para NÃO virar substitution do Cloud Build)
        kubectl -n aplicacao delete secret db-credentials --ignore-not-found
        kubectl -n aplicacao create secret generic db-credentials \
          --from-literal=DB_USER="$$DB_USER" \
          --from-literal=DB_PASSWORD="$$DB_PASSWORD" \
          --from-literal=DB_NAME="$$DB_NAME"

        # Aplica manifests do MariaDB
        kubectl apply -f k8s/pvc-mariadb.yaml
        kubectl apply -f k8s/deploy-mariadb.yaml
        kubectl apply -f k8s/svc-mariadb.yaml

        # Aplica manifests da Web
        kubectl apply -f k8s/deploy-web.yaml
        kubectl apply -f k8s/svc-web.yaml

        # Atualiza imagem da aplicação para o commit atual
        kubectl -n aplicacao set image deployment/web \
          web="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:$SHORT_SHA"

        # Aguarda rollouts
        kubectl -n aplicacao rollout status deployment/mariadb --timeout=300s
        kubectl -n aplicacao rollout status deployment/web --timeout=300s

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:$SHORT_SHA"
